spring.application.name=backend
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

apis.env=${APIS_ENV}

# MongoDB configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://jhonladines2019_db_user:Jhonladines2019@cluster0.xfwafs9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
